UPDATE ModifierArguments
SET Value = 'DIPLOMACY_AGENDA_NEG_AMT_LARGE'
WHERE ModifierId = 'MACHIAVELLI_MOD_AGENDA_THE_SPIDER'
  AND Name = 'AwardAmtType1';

UPDATE LeaderTraits
SET TraitType = 'TRAIT_LEADER_MACHIAVELLI_ABILITY'
WHERE TraitType LIKE '%_ABILITY';

DELETE FROM TraitModifiers
WHERE ModifierId IN (
    'MACHIAVELLI_MOD_INFLUENCE',
    'MACHIAVELLI_GOLD_ACTION_ACCEPT',
    'MACHIAVELLI_GOLD_ACTION_REJECT'
);

UPDATE Modifiers
SET ModifierType = 'MODIFIER_DIPLOMACY_AGENDA'
WHERE ModifierId = 'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET';

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT
    'TRAIT_LEADER_MACHIAVELLI_ABILITY',
    'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
WHERE NOT EXISTS (
    SELECT 1
    FROM TraitModifiers
    WHERE TraitType = 'TRAIT_LEADER_MACHIAVELLI_ABILITY'
      AND ModifierId = 'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
);

UPDATE ModifierArguments
SET Value = 'DIPLOMACY_AGENDA_NEG_AMT_LARGE'
WHERE ModifierId = 'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
  AND Name = 'AwardAmtType1';

UPDATE ModifierArguments
SET Value = 'DIPLOMACY_AGENDA_AMT_LARGE'
WHERE ModifierId = 'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
  AND Name = 'AwardAmtType2';
