UPDATE ModifierArguments
SET Value = 'DIPLOMACY_AGENDA_NEG_AMT_LARGE'
WHERE ModifierId = 'MACHIAVELLI_MOD_AGENDA_THE_SPIDER'
  AND Name = 'AwardAmtType1';

UPDATE LeaderTraits
SET TraitType = 'TRAIT_LEADER_MACHIAVELLI_ABILITY'
WHERE TraitType LIKE '%_ABILITY';

DELETE FROM TraitModifiers
WHERE ModifierId IN (
    'MACHIAVELLI_MOD_INFLUENCE',
    'MACHIAVELLI_GOLD_ACTION_ACCEPT',
    'MACHIAVELLI_GOLD_ACTION_REJECT',
    'MACHIAVELLI_MOD_AGENDA_SPIDER'
);

INSERT OR IGNORE INTO Modifiers
    (ModifierId, ModifierType, NewOnly, OwnerRequirementSetId, OwnerStackLimit, Permanent, RunOnce, SubjectRequirementSetId, SubjectStackLimit)
VALUES
    ('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET',
     'MODIFIER_DIPLOMACY_AGENDA',
     0, NULL, NULL, 0, 0, NULL, NULL);

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT
    'TRAIT_LEADER_MACHIAVELLI_ABILITY',
    'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
WHERE NOT EXISTS (
    SELECT 1
    FROM TraitModifiers
    WHERE TraitType = 'TRAIT_LEADER_MACHIAVELLI_ABILITY'
      AND ModifierId = 'ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET'
);

INSERT INTO ModifierArguments
    (ModifierId, Name, Extra, SecondExtra, Type, Value)
VALUES
-- Display
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'ModName',        NULL, NULL, NULL, 'LOC_DIPLOMACY_AGENDA_WITHOUT_REGRET_NAME'),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'Tooltip',        NULL, NULL, NULL, 'LOC_DIPLOMACY_AGENDA_WITHOUT_REGRET_DESC'),

-- Core logic
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'WeightType',     NULL, NULL, NULL, 'DIPLOMACY_AGENDA_COMPARE_NUM_OWNED_TILES'),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'FirstMeetDelay', NULL, NULL, NULL, 20),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'UpdateFreq',     NULL, NULL, NULL, 1),

-- Awards
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'AwardTo1',       NULL, NULL, NULL, 'DIPLOMACY_AGENDA_AWARD_HIGHEST'),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'AwardAmtType1',  NULL, NULL, NULL, 'DIPLOMACY_AGENDA_NEG_AMT_MEDIUM'),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'AwardTo2',       NULL, NULL, NULL, 'DIPLOMACY_AGENDA_AWARD_LOWEST'),
('ASHOKA_ALT_MOD_AGENDA_WITHOUT_REGRET', 'AwardAmtType2',  NULL, NULL, NULL, 'DIPLOMACY_AGENDA_AMT_MEDIUM');